-- Nuvora Store Phase 4 schema.
-- Apply this file in the Supabase SQL Editor before running seed.sql.

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  price numeric(12, 2) not null check (price >= 0),
  image_url text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete set null,
  customer_name text not null,
  email text not null,
  address text not null,
  total numeric(12, 2) not null check (total >= 0),
  status text not null default 'pending'
    check (status in ('pending', 'confirmed')),
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders (id) on delete cascade,
  product_id bigint not null references public.products (id) on delete restrict,
  quantity integer not null check (quantity > 0),
  price numeric(12, 2) not null check (price >= 0),
  created_at timestamptz not null default now()
);

create index if not exists orders_user_id_idx on public.orders (user_id);
create index if not exists order_items_order_id_idx on public.order_items (order_id);
create index if not exists order_items_product_id_idx on public.order_items (product_id);

alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- Public clients may read the catalog, but cannot change it.
revoke all on table public.products from anon, authenticated;
grant select on table public.products to anon, authenticated;

drop policy if exists "Products are readable by everyone" on public.products;
create policy "Products are readable by everyone"
  on public.products
  for select
  to anon, authenticated
  using (true);

-- Orders remain inaccessible to browser clients until a later phase adds
-- narrowly scoped policies for authenticated customers.
revoke all on table public.orders, public.order_items from anon, authenticated;